basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket, name='basket'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
    path('auth-add/', views.auth_basket_add, name='auth_basket_add'),
    path('auth-delete/', views.auth_basket_remove, name='auth_basket_remove'),
    path('auth-update/', views.auth_basket_update, name='auth_basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/all/', views.all, name='all'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('item/<slug:slug>/', views.item, name='item'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add/', views.wishlist_add, name='wishlist_add'),
    path('remove/', views.wishlist_remove, name='wishlist_remove'),
    path('not-auth-add/', views.not_auth_wishlist_add,
         name='not_auth_wishlist_add'),
    path('not-auth-remove/', views.not_auth_wishlist_delete,
         name='not_auth_wishlist_remove'),
]

wishlist/models.py
from django.conf import settings
from django.db import models

from store.models import Product


class List(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-added',)

    def __str__(self):
        return str(self.user)

wishlist/views.py
from django.contrib.auth.decorators import login_required
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render

from account.models import UserBase
from store.models import Product
from wishlist.wishlist import WishList

from .models import List


@login_required
def wishlist_add(request):
    '''
    Adds specific product to user's wishlist
    '''
    user = get_object_or_404(UserBase, id=request.user.id)
    if request.POST.get('action') == 'post':
        itemID = int(request.POST.get('itemid'))
        product = get_object_or_404(Product, id=itemID)
        if List.objects.filter(user=user, item=product).exists():
            pass
        else:
            List.objects.create(user=user, item=product)

        response = JsonResponse({'success': 'Added'})
        return response


@login_required
def wishlist_remove(request):
    '''
    Removes specific product from user's wishlist
    '''
    user = get_object_or_404(UserBase, id=request.user.id)
    if request.POST.get('action') == 'post':
        itemID = int(request.POST.get('itemid'))
        product = get_object_or_404(Product, id=itemID)
        List.objects.filter(user=user, item=product).delete()

        response = JsonResponse({'success': 'Removed'})
        return response


def wishlist(request):
    if request.user.is_authenticated:
        user = request.user.id
        context = List.objects.filter(user=user)
        if context:
            error = None
        else:
            error = 'Your wishlist is empty'
    else:
        context = WishList(request)
        error = None
    return render(request, 'wishlist/wishlist.html', {'wishlist': context, 'error': error})


def not_auth_wishlist_add(request):
    wishlist = WishList(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('itemid'))
        product = get_object_or_404(Product, id=product_id)
        wishlist.add(product=product)
        response = JsonResponse({'success': 'Added'})
        return response


def not_auth_wishlist_delete(request):
    wishlist = WishList(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('itemid'))
        wishlist.delete(product=product_id)
        response = JsonResponse({'Success': True})
        return response

templates/wishlist/wishlist.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}Wishlist{% endblock %}
{% block nav-wishlist %}
text-secondary
{% endblock %}
{% block content %}
<div class="col-12 px-5 py-5">
	<a class="btn btn-outline-dark ml-5" onclick="Previous()">&#x2190; Continue Shopping</a>
</div>
<div class="album py-5 bg-light">
	<div class="container">
	{% if user.is_authenticated %}
		{% if error != None %}
		<h5 class="text-center">{{error}}</h5>
		{% else %}
		{% endif %}
		<div class="row row-cols-2 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3">
			{% for wishitem in wishlist %}
			<div class="col">
              <div class="card shadow-sm">
              	<a href="{% url 'store:item' wishitem.item.slug %}"><img src="{{ wishitem.item.image.url }}" class="img-fluid" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"></a>
                <div class="card-body">
                <div class="card-title">
                  <h5 class="product-title">{{ wishitem.item.title }}</h5>
                </div>
                <div class="d-flex ifstock justify-content-between align-items-center pb-3">
                  <div class="ifstock-container">
                    <p class="card-text d-inline">
                      {% if wishitem.item.in_stock == False %}
                        Out of Stock
                      {% else %}
                        In Stock
                      {% endif %}
                    </p>
                  </div>
                  <div class="price-container">
                    <p class="d-inline">${{ wishitem.item.price }}</p>
                  </div>
                </div>
                <div class="row d-flex justify-content-between align-items-center">
                  	<div class="col-12">
						{% if wishitem.item.in_stock == False %}
						<div class="col-12 btn-group">
							<button type="button" data-index="{{wishitem.item.id}}" class="single-wl btn btn-sm btn-outline-secondary btn-product wishlst wishlst-remove">Remove from wishlist</button>
						</div>
						{% else %}
						<div class="col-12 auto-group btn-group">
							<button type="button" data-index="{{wishitem.item.id}}" class="btn btn-sm btn-outline-secondary btn-product wishlst-remove">Remove from wishlist</button>
							<button type="button" data-index="{{wishitem.item.id}}"
							class="btn btn-sm btn-outline-secondary btn-product add-button">Add to basket</button>
						</div>
					</div>
                    {% endif %}
                </div>
                </div>
              </div>
            </div>
			{% endfor %}
		</div>
	{% else %}
		{% with total_quantity=wishlist|length %}
		{% if total_quantity > 0 %}
		<div class="row row-cols-2 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3">
			{% for item in wishlist %}
			<div class="col">
				<div class="card shadow-sm">
					<a href="{% url 'store:item' item.product.slug %}"><img src="{{ item.product.image.url }}"
							class="img-fluid" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"></a>
					<div class="card-body">
						<div class="card-title">
							<h5 class="product-title">{{ item.product.title }}</h5>
						</div>
						<div class="d-flex ifstock justify-content-between align-items-center pb-3">
							<div class="ifstock-container">
								<p class="card-text d-inline">
									{% if item.product.in_stock == False %}
									Out of Stock
									{% else %}
									In Stock
									{% endif %}
								</p>
							</div>
							<div class="price-container">
								<p class="d-inline">${{ item.product.price }}</p>
							</div>
						</div>
						<div class="row justify-content-between align-items-center">
							<div class="col-12">
								{% if item.product.in_stock == False %}
								<div class="col-12 btn-group">
									<button type="button" data-index="{{item.product.id}}"
										class="single-wl btn btn-sm btn-outline-secondary btn-product notauth-wishlst-remove">Remove
										from wishlist
									</button>
								</div>
								{% else %}
								<div class="col-12 auto-group btn-group">
									<button type="button" data-index="{{item.product.id}}"
										class="btn btn-sm btn-outline-secondary btn-product notauth-wishlst-remove">Remove
										from wishlist
									</button>
									<button type="button" data-index="{{item.product.id}}"
										class="btn btn-sm btn-outline-secondary btn-product add-button">Add to
										basket
									</button>
								</div>
								{% endif %}
							</div>
						</div>
					</div>
				</div>
			</div>
			{% endfor %}
		</div>
		{% else %}
		<h4 class="text-center">Your wishlist is empty</h4>
		{% endif %}
		{% endwith %}
		{% endif %}
	</div>
</div>
<script>
	function Previous() {
		window.history.back()
	}

	$(document).on('click', '.add-button', function (e) {
		e.preventDefault();
		$.ajax({
			type: 'POST',
			url: '{% url "basket:basket_add" %}',
			data: {
				productid: $(this).data('index'),
				quantity: '1',
				size: '38',
				csrfmiddlewaretoken: "{{csrf_token}}",
				action: 'post',
			},
			success: function (json) {
				document.getElementById("basket-count").innerHTML = json.quantity
			},
			error: function (xhr, errmsg, err) {}
		});
	})

	$(document).on('click', '.wishlst-remove', function (e) {
		e.preventDefault();
		$.ajax({
			type: 'POST',
			url: '{% url "wishlist:wishlist_remove" %}',
			data: {
				itemid: $(this).data('index'),
				csrfmiddlewaretoken: "{{csrf_token}}",
				action: 'post',
			},
			success: function (json) {
				window.location.reload()
			},
			error: function (xhr, errmsg, err) {}
		});
	})

	$(document).on('click', '.notauth-wishlst-remove', function (e) {
		e.preventDefault();
		$.ajax({
			type: 'POST',
			url: '{% url "wishlist:not_auth_wishlist_remove" %}',
			data: {
				itemid: $(this).data('index'),
				csrfmiddlewaretoken: "{{csrf_token}}",
				action: 'post',
			},
			success: function (json) {
				window.location.reload()
			},
			error: function (xhr, errmsg, err) {}
		});
	})

	$(window).ready(function() {
      if ($(window).width() <= 575) {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group-vertical';
        });
      }
      else {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group';
        });
      }
    });

    $(window).resize(function() {
      if ($(window).width() <= 575) {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group-vertical';
        });
      }
      else {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group';
        });
      }
    });
</script>
{% endblock %}