basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket, name='basket'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
    path('auth-add/', views.auth_basket_add, name='auth_basket_add'),
    path('auth-delete/', views.auth_basket_remove, name='auth_basket_remove'),
    path('auth-update/', views.auth_basket_update, name='auth_basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/all/', views.all, name='all'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('item/<slug:slug>/', views.item, name='item'),
]

wishlist/urls.py
from django.urls import path

from . import views

app_name = 'wishlist'

urlpatterns = [
    path('', views.wishlist, name='wishlist'),
    path('add/', views.wishlist_add, name='wishlist_add'),
    path('remove/', views.wishlist_remove, name='wishlist_remove'),
    path('not-auth-add/', views.not_auth_wishlist_add,
         name='not_auth_wishlist_add'),
    path('not-auth-remove/', views.not_auth_wishlist_delete,
         name='not_auth_wishlist_remove'),
]

basket/models.py
from django.conf import settings
from django.db import models

from store.models import Product


class Basket(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    item = models.ForeignKey(Product, on_delete=models.CASCADE)
    size = models.CharField(max_length=2)
    quantity = models.PositiveIntegerField(default=1)
    added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-added',)

    def price(self):
        return float(self.item.price * self.quantity)

    def __str__(self):
        return str(self.user)

store/models.py
from django.db import models
from django.urls import reverse


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(in_stock=True)


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def get_absolute_url(self):
        return reverse('store:category', args=[self.slug])

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(
        Category, related_name='product', on_delete=models.CASCADE)
    title = models.CharField(max_length=24)
    description = models.TextField(blank=True)
    color = models.CharField(max_length=20, blank=True)
    image = models.ImageField(upload_to='images/')
    in_stock = models.BooleanField(default=False)
    promotion = models.BooleanField(default=False)
    price = models.FloatField(max_length=6)
    created = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=255)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        verbose_name_plural = 'Products'
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:item', args=[self.slug])

    def __str__(self):
        return self.title

basket/views.py
from django.contrib.auth.decorators import login_required
from django.db.models import Sum
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render

from account.models import UserBase
from store.models import Product

from .basket import Basket
from .models import Basket as BasketModel


def basket(request):
    if request.user.is_authenticated:
        user = request.user.id
        total_quantity = BasketModel.objects.filter(user=user).aggregate(
            basket_quantity=Sum('quantity'))['basket_quantity']
        total_price = 0
        for basketitem in BasketModel.objects.filter(user=user):
            total_price += basketitem.item.price * basketitem.quantity
        context = BasketModel.objects.filter(user=user)
        if context:
            error = None
        else:
            error = 'Your basket is empty'
    else:
        context = None
        error = None
        total_price = None
        total_quantity = None
    return render(request, 'basket/basket.html', {'basketmodel': context, 'error': error, 'total_price': total_price, 'total_quantity': total_quantity})


def basket_add(request):
    '''
    Handles data captured from ajax and adds product to basket,
    updates the actual amount of products in basket.
    '''
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        quantity = int(request.POST.get('quantity'))
        size = int(request.POST.get('size'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, quantity=quantity, size=size)
        basket_quantity = basket.__len__()
        response = JsonResponse({'quantity': basket_quantity})
        return response


def basket_delete(request):
    '''
    Handles request to delete product from basket
    '''
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)
        response = JsonResponse({'Success': True})
        return response


def basket_update(request):
    '''
    Handles request to update product quantity or size from basket
    '''
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        quantity = int(request.POST.get('quantity'))
        size = int(request.POST.get('size'))
        basket.update(product=product_id, quantity=quantity, size=size)

        response = JsonResponse({'Success': True})
        return response


@login_required
def auth_basket_add(request):
    user = get_object_or_404(UserBase, id=request.user.id)
    if request.POST.get('action') == 'post':
        itemID = int(request.POST.get('itemid'))
        quantity = int(request.POST.get('quantity'))
        size = int(request.POST.get('size'))
        product = get_object_or_404(Product, id=itemID)
        if BasketModel.objects.filter(user=user, item=product).exists():
            pass
        else:
            BasketModel.objects.create(
                user=user, item=product, quantity=quantity, size=size)

        response = JsonResponse({'success': 'Added'})
        return response


@login_required
def auth_basket_remove(request):
    user = get_object_or_404(UserBase, id=request.user.id)
    if request.POST.get('action') == 'post':
        itemID = int(request.POST.get('itemid'))
        product = get_object_or_404(Product, id=itemID)
        BasketModel.objects.filter(user=user, item=product).delete()

        response = JsonResponse({'success': 'Removed'})
        return response


@login_required
def auth_basket_update(request):
    user = get_object_or_404(UserBase, id=request.user.id)
    if request.POST.get('action') == 'post':
        itemID = int(request.POST.get('productid'))
        product = get_object_or_404(Product, id=itemID)
        quantity = int(request.POST.get('quantity'))
        size = int(request.POST.get('size'))
        BasketModel.objects.filter(user=user, item=product).update(
            quantity=quantity, size=size)

        response = JsonResponse({'success': 'Removed'})
        return response

store/views.py
from django.http import request
from django.shortcuts import get_object_or_404, render

from .models import *


def home(request):
    return render(request, 'store/home.html')


def all(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'store/all.html', context)


def category(request, slug):
    category_show = get_object_or_404(Category, slug=slug)
    products = Product.objects.filter(category_id=category_show)
    context = {
        'category_show': category_show,
        'products': products,
    }
    return render(request, 'store/category.html', context)


def item(request, slug):
    product = get_object_or_404(Product, slug=slug)

    context = {
        'product': product,
    }
    return render(request, 'store/item.html', context)

templates/store/all.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}All Products{% endblock %}
{% block nav-home %}
    text-white
{% endblock %}
{% block nav-products %}
    text-secondary
{% endblock %}
{% block content %}
<main>

    <section class="py-5 text-center container">
      <div class="row py-lg-5">
        <div class="col-lg-6 col-md-8 mx-auto">
          <h1 class="fw-light">All products</h1>
          <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in commodo neque. Sed vitae erat porttitor, dignissim ante at, dictum risus. Cras ut sapien congue, elementum ligula vel, finibus diam.</p>
        </div>
      </div>
    </section>
  
    <div class="album py-5 bg-light">
      <div class="container">
        <div class="row row-cols-2 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3">
        {% for product in products %}
          <div class="col">
            <div class="card shadow-sm">
              <a href="{% url 'store:item' product.slug %}"><img src="{{ product.image.url }}" class="img-fluid" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"></a>
              <div class="row card-body">
                <div class="col-12 card-title">
                  <h5 class="product-title">{{ product.title }}</h5>
                </div>
                <div class="col-12 d-flex ifstock justify-content-between align-items-center pb-3">
                  <div class="ifstock-container">
                    <p class="card-text d-inline">
                      {% if product.in_stock == False %}
                        Out of Stock
                      {% else %}
                        In Stock
                      {% endif %}
                    </p>
                  </div>
                  <div class="price-container">
                    <p class="d-inline">${{ product.price }}</p>
                  </div>
                </div>
                <div class="col-12 d-flex justify-content-between align-items-center">
                  <div class="col-12 btn-group">
                  {% if user.is_authenticated %}
                    {% if product.in_stock == False %}
                    <div class="col-12 btn-group">
                      <button type="button" data-index="{{product.id}}" class="single btn btn-sm btn-outline-secondary btn-product wishlst wishlist-add">Add to wishlist</button>
                    </div>
                    {% else %}
                    <div class="col-12 auto-group btn-group">
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product wishlist-add">Add to wishlist</button>
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product auth-add-button">Add to basket</button>
                    </div>
                    {% endif %}
                  {% else %}
                    {% if product.in_stock == False %}
                    <div class="col-12 btn-group">
                      <button type="button" data-index="{{product.id}}" class="single btn btn-sm btn-outline-secondary btn-product wishlst notauth-wishlist-add">Add to wishlist</button>
                    </div>
                    {% else %}
                    <div class="col-12 auto-group btn-group">
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product notauth-wishlist-add">Add to wishlist</button>
                      <button type="button" data-index="{{product.id}}"
                      class="btn btn-sm btn-outline-secondary btn-product add-button">Add to basket</button>
                    </div>
                    {% endif %}
                  {% endif %}
                </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
        </div>
      </div>
    </div>
</main>
<script>
    $(document).on('click', '.add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $(this).data('index'),
                quantity: '1',
                size: '38',
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {
                document.getElementById("basket-count").innerHTML = json.quantity
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.notauth-wishlist-add', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "wishlist:not_auth_wishlist_add" %}',
            data: {
                itemid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {},
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.wishlist-add', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "wishlist:wishlist_add" %}',
            data: {
                itemid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {},
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.auth-add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:auth_basket_add" %}',
            data: {
                itemid: $(this).data('index'),
                quantity: '1',
                size: '38',
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {},
            error: function (xhr, errmsg, err) {}
        });
    })

    $(window).ready(function() {
      if ($(window).width() <= 490) {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group-vertical';
        });
      }
      else {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group';
        });
      }
    });

    $(window).resize(function() {
      if ($(window).width() <= 490) {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group-vertical';
        });
      }
      else {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group';
        });
      }
    });
</script>
{% endblock %}

templates/store/basket.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}Basket{% endblock %}
{% block nav-home %}
text-white
{% endblock %}
{% block content %}
<div class="col-12 px-5 pt-5">
	<a class="btn btn-outline-dark ml-5" onclick="Previous()">&#x2190; Continue Shopping</a>
</div>
<div class="container my-5 p-0 border">
	<div class="row p-3">
		{% with total_quantity=basket|length %}
		{% if total_quantity > 0 %}
		<div class="basket-info pt-1">
			<h2>Your basket</h2>
			<h4 class="mb-4">Total: <span class="text-muted">({% with total_quantity=basket|length %}
					{% if total_quantity > 0 %}
					{{total_quantity}}
					{% endif %}
					{% endwith %} {% if total_quantity > 1 %} Products {% else %} Product {% endif %})
					{{basket.get_total_price}}$</span></h4>
		</div>
		<div class="col-9 col-md-8">
			{% for item in basket %}
			<section class="items">
				<div class="item border row">
					<div class="col-4">
						<img class="img-fluid" id="productImg{{item.product.id}}" src="{{ item.product.image.url }}">
					</div>
					<div class="col-5 p-3">
						<h5 id="productTitle{{item.product.id}}">{{item.product.title}}</h5>
						<br>
						<h6 id="size{{item.product.id}}" data-index="{{item.size}}">Size: {{item.size}}</h6>
						<h6 id="qty{{item.product.id}}" data-index="{{item.quantity}}">Quantity: {{item.quantity}}</h6>
					</div>
					<div class="col-3 p-3" style="text-align: end; position:relative;">
						<h5 id="productPrc{{item.product.id}}" data-index="{{item.price}}" class="text-muted price-info">{{item.quantity}} x ${{item.price}}</h5>
						<hr style="margin-left: auto; max-width: 100px;">
						<h5 id="totalPrc{{item.product.id}}" data-index="{{item.total_price}}" class="text-muted">${{item.total_price}}</h5>
						<button type="button" class="edit-button m-3" data-bs-toggle="modal" data-index="{{item.product.id}}" data-bs-target="#exampleModal" title="Edit">
							<svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor"
								class="basket-svg" viewBox="0 0 16 16" class="note-edit">
								<path
									d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z" />
								<path fill-rule="evenodd"
									d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z" />
							</svg>
						</button>
						<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
							<div class="modal-dialog modal-dialog-centered">
								<div class="modal-content">
								<div class="modal-header">
									<h5 class="modal-title" id="title"></h5>
									<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
								</div>
								<div class="modal-body">
									<div class="row">
										<div class="col-6">
											<img class="img-fluid" id="img" src="">
										</div>
										<div class="col-6" style="text-align: end; position:relative;">
											<table class="table table-sm table-borderless text-center">
												<tbody>
													<tr>
														<td class="pb-0">Select size</td>
														<td class="pb-0">Quantity</td>
													</tr>
													<tr>
														<td>
															<select name="size" id="edit-size">
																<option id="size38" value="38">38</option>
																<option id="size39" value="39">39</option>
																<option id="size40" value="40">40</option>
																<option id="size41" value="41">41</option>
																<option id="size42" value="42">42</option>
																<option id="size43" value="43">43</option>
																<option id="size44" value="44">44</option>
															</select>
														</td>
														<td>
															<select name="quantity" id="edit-quantity" style="margin-left: 0;" onchange="AutoPrice()">
																<option id="opt1" value="1">1</option>
																<option id="opt2" value="2">2</option>
																<option id="opt3" value="3">3</option>
															</select>
														</td>
													</tr>
												</tbody>
											</table>
											<h5 class="text-muted" id="modal-price"></h5>
										</div>
									</div>
								</div>
								<div class="modal-footer">
									<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
									<button type="button" value="" id="update" class="btn btn-primary">Save changes</button>
								</div>
								</div>
							</div>
						</div>
						<button type="button" class="remove-button m-3" data-index="{{item.product.id}}" title="Remove">
							<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor"
								class="basket-svg" viewBox="0 0 16 16">
								<path
									d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z" />
								<path
									d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z" />
							</svg>
						</button>
					</div>
				</div>
			</section>
			{% endfor %}
		</div>
		<div class="col-3 col-md-4 p-3 border">
			Payments
		</div>
		{% else %}
		<h1 id="no-items">No items in basket</h1>
		{% endif %}
		{% endwith %}
	</div>
</div>
<script>
	function Previous() {
		window.history.back()
	}

	function AutoPrice() {
		price = $(`#productPrc${product}`).data('index');
		selector = document.getElementById('edit-quantity');
		selected_quantity = selector.options[selector.selectedIndex].text;
		document.getElementById('modal-price').innerText = "$" + price * selected_quantity;
	}

	$(document).on('click', '.edit-button', function (e) {
		e.preventDefault();
		product = $(this).data('index');
		document.getElementById('update').value = product;
		title = document.getElementById(`productTitle${product}`).innerText;
		document.getElementById('title').innerText = title;
		img = document.getElementById(`productImg${product}`).src;
		document.getElementById('img').src = img;
		price = $(`#totalPrc${product}`).data('index');
		document.getElementById('modal-price').innerText = "$" + price;
		selected_quantity = $(`#qty${product}`).data('index');
		document.getElementById(`opt${selected_quantity}`).selected = true;
		selected_size = $(`#size${product}`).data('index');
		document.getElementById(`size${selected_size}`).selected = true;
	})

	$(document).on('click', '#update', function (e) {
		e.preventDefault();
		$.ajax({
				type: 'POST',
				url: '{% url "basket:basket_update" %}',
				data: {
					productid: $('#update').val(),
					quantity: $('#edit-quantity option:selected').text(),
					size: $('#edit-size option:selected').text(),
					csrfmiddlewaretoken: "{{csrf_token}}",
					action: 'post',
				},
				success: function (json) {
					window.location.reload(true);
				},
				error: function (xhr, errmsg, err) {}
			});
	})

	$(document).on('click', '.remove-button', function (e) {
		e.preventDefault();
		$.ajax({
			type: 'POST',
			url: '{% url "basket:basket_delete" %}',
			data: {
				productid: $(this).data('index'),
				csrfmiddlewaretoken: "{{csrf_token}}",
				action: 'post',
			},
			success: function (json) {
				window.location.reload(true);
			},
			error: function (xhr, errmsg, err) {}
		});
	})
</script>
{% endblock content %}

templates/store/category.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}{{ category_show.name }}{% endblock %}
{% block nav-home %}
text-white
{% endblock %}
{% block nav-products %}
text-secondary
{% endblock %}
{% block content %}
<main>

  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">{{ category_show.name }}</h1>
        <p class="lead text-muted">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent in commodo neque.
          Sed vitae erat porttitor, dignissim ante at, dictum risus. Cras ut sapien congue, elementum ligula vel,
          finibus diam.</p>
      </div>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row row-cols-2 row-cols-sm-2 row-cols-lg-3 row-cols-xl-4 g-3">
        {% for product in products %}
        <div class="col">
            <div class="card shadow-sm">
              <a href="{% url 'store:item' product.slug %}"><img src="{{ product.image.url }}" class="img-fluid" role="img" preserveAspectRatio="xMidYMid slice" focusable="false"></a>
              <div class="card-body">
                <div class="col-12 card-title">
                  <h5 class="product-title">{{ product.title }}</h5>
                </div>
                <div class="col-12 d-flex ifstock justify-content-between align-items-center pb-3">
                  <div class="ifstock-container">
                    <p class="card-text d-inline">
                      {% if product.in_stock == False %}
                        Out of Stock
                      {% else %}
                        In Stock
                      {% endif %}
                    </p>
                  </div>
                  <div class="price-container">
                    <p class="d-inline">${{ product.price }}</p>
                  </div>
                </div>
                <div class="col-12 d-flex justify-content-between align-items-center">
                  <div class="col-12 btn-group">
                  {% if user.is_authenticated %}
                    {% if product.in_stock == False %}
                    <div class="col-12 btn-group">
                      <button type="button" data-index="{{product.id}}" class="single btn btn-sm btn-outline-secondary btn-product wishlst wishlist-add">Add to wishlist</button>
                    </div>
                    {% else %}
                    <div class="col-12 auto-group btn-group">
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product wishlist-add">Add to wishlist</button>
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product auth-add-button">Add to basket</button>
                    </div>
                    {% endif %}
                  {% else %}
                    {% if product.in_stock == False %}
                    <div class="col-12 btn-group">
                      <button type="button" data-index="{{product.id}}" class="single btn btn-sm btn-outline-secondary btn-product wishlst notauth-wishlist-add">Add to wishlist</button>
                    </div>
                    {% else %}
                    <div class="col-12 auto-group btn-group">
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product notauth-wishlist-add">Add to wishlist</button>
                      <button type="button" data-index="{{product.id}}" class="btn btn-sm btn-outline-secondary btn-product add-button">Add to basket</button>
                    </div>
                    {% endif %}
                  {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
  </div>
</main>
<script>
    $(document).on('click', '.add-button', function (e) {
        e.preventDefault();
        console.log($(this).data('index'))
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productid: $(this).data('index'),
                quantity: '1',
                size: '38',
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {
                document.getElementById("basket-count").innerHTML = json.quantity
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.auth-add-button', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:auth_basket_add" %}',
            data: {
                itemid: $(this).data('index'),
                quantity: '1',
                size: '38',
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {},
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.notauth-wishlist-add', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "wishlist:not_auth_wishlist_add" %}',
            data: {
                itemid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {},
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.wishlist-add', function (e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "wishlist:wishlist_add" %}',
            data: {
                itemid: $(this).data('index'),
                csrfmiddlewaretoken: "{{csrf_token}}",
                action: 'post',
            },
            success: function (json) {},
            error: function (xhr, errmsg, err) {}
        });
    })

    $(window).ready(function() {
      if ($(window).width() <= 490) {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group-vertical';
        });
      }
      else {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group';
        });
      }
    });

    $(window).resize(function() {
      if ($(window).width() <= 490) {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group-vertical';
        });
      }
      else {
        Array.from(document.querySelectorAll('.auto-group')).forEach(elem => {
          elem.className = 'col-12 auto-group btn-group';
        });
      }
    });
</script>
{% endblock %}