core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('wishlist/', include('wishlist.urls', namespace='wishlist')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path

from . import views

app_name = 'orders'

urlpatterns = [
    path('dashboard/', views.dashboard, name='dashboard'),
    path('order-done/', views.order_done, name='order_done'),
    path('add/', views.add, name='add'),
]

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.home, name='home'),
    path('category/all/', views.all, name='all'),
    path('category/<slug:slug>/', views.category, name='category'),
    path('item/<slug:slug>/', views.item, name='item'),
]

orders/models.py
from django.conf import settings
from django.db import models
from django.db.models.fields import BooleanField

from store.models import Product


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, null=True, related_name='order_user')
    product = models.ForeignKey(
        Product, related_name='order_items', on_delete=models.SET_NULL, null=True)
    size = models.CharField(max_length=2)
    quantity = models.PositiveIntegerField(default=1)
    full_name = models.CharField(max_length=60)
    address1 = models.CharField(max_length=50)
    address2 = models.CharField(max_length=50)
    postcode = models.CharField(max_length=12)
    town = models.CharField(max_length=50)
    country = models.CharField(max_length=35)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    total_paid = models.DecimalField(max_digits=5, decimal_places=2)
    order_key = models.CharField(max_length=200)
    billing_status = models.BooleanField(default=False)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return str(self.user)

orders/views.py
from datetime import datetime

from django.contrib.auth.decorators import login_required
from django.http import request
from django.http.response import JsonResponse
from django.shortcuts import get_object_or_404, render

from basket.basket import Basket
from basket.models import Basket as BasketModel
from store.models import Product

from .models import Order

now = datetime.now()


@login_required
def add(request):
    '''
    Creates order if payment has been completed
    '''
    if request.POST.get('action') == 'post':
        order_key = request.POST.get('order_key')
        user_id = request.user.id
        total_price = 0
        for basketitem in BasketModel.objects.filter(user=user_id):
            total_price += basketitem.item.price * basketitem.quantity
        baskettotal = total_price
        full_name = request.POST.get('custName')
        town = request.POST.get('custTown')
        address1 = request.POST.get('custAdd')
        address2 = request.POST.get('custAdd2')
        postcode = request.POST.get('custCode')
        country = request.POST.get('custCountry')

        # Check if order exists
        if Order.objects.filter(order_key=order_key).exists():
            pass
        else:
            for basketitem in BasketModel.objects.filter(user=user_id):
                product = get_object_or_404(Product, id=basketitem.item.id)
                order = Order.objects.create(user_id=user_id, product=product, size=basketitem.size, quantity=basketitem.quantity, full_name=full_name, address1=address1,
                                             address2=address2, postcode=postcode, town=town, country=country, total_paid=baskettotal, order_key=order_key)

        response = JsonResponse({'success': 'Return authenticated orders'})
        return response


def payment_confirmation(data):
    '''
    Updates billing status to True if order_key captured by stripe exists
    '''
    Order.objects.filter(order_key=data).update(billing_status=True)


@login_required
def dashboard(request):
    user = request.user.id
    order = Order.objects.filter(user=user, billing_status=True)
    return render(request, 'orders/dashboard.html', {'orders': order})


@login_required
def order_done(request):
    BasketModel.objects.filter(user=request.user.id).delete()
    return render(request, 'orders/order_done.html')

templates/orders/dashboard.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}
{% block nav-dashboard %}
text-secondary
{% endblock %}
{% block content %}
<div class="container my-5 p-4 border">
    <div class="row">
        <div class="col-12">
            <h3>Dashboard</h1>
            <p>Manage your orders and personal details</p>
				{% for order in orders %}
				<div class="row text-center">
					<div class="col-12 col-md-7 col-lg-6 col-xl-6 p-2 border order-1 order-md-1">
						Product details
					</div>
					<div class="col-12 col-md-5 col-lg-6 col-xl-6 p-2 border order-4 order-md-2">
						Order details
					</div>
					<div class="col-12 col-md-4 col-lg-3 col-xl-2 border order-2 order-md-3">
						<a href="{% url 'store:item' order.product.slug %}"><img class="img-fluid" src="{{order.product.image.url}}"></a>
					</div>
					<div class="col-12 col-md-3 col-lg-3 col-xl-4 border p-3 order-3 order-md-4">
						<h5>{{order.product.title}}</h5>
						<h5>{{order.product.color}}</h5>
						<h6 class="pt-4">Product size: {{order.size}}</h6>
						<h6>Quantity: {{order.quantity}}</h6>

					</div>
					<div class="col-12 col-md-5 col-lg-6 col-xl-6 border p-3 order-5 order-md-5">
						<h5 class="pb-3">Shipping to: {{order.country}}<h5>
						<h6>{{order.town}}, {{order.address1}} {{order.address2}}</h6>
						<h6>{{order.postcode}}</h6>
						<h6 class="pt-3">Ordered: {{order.created}}</h6>
					</div>
					<div class="col-0 col-lg-1 order-md-5"></div>
				</div>
				{% endfor %}
			</div>
        </div>
    </div>
</div>
{% endblock %}

templates/orders/order_done.html
{% extends 'store/base.html' %}
{% load static %}
{% block title %}Order has been placed{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row no-gutter">
        <div class="col-md-12">
            <div class="login d-flex align-items-center py-5">
                <div class="container mt-5 mb-5">
                    <div class="row d-flex align-items-center justify-content-center p-5 border">
                        <div class="col-md-6 text-center">
                            <h6>Order has been placed.
                                Checkout your <a href="{% url 'orders:dashboard' %}">Dashboard</a> and email.
                            </h6>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}